### ISSUE TITLE
Word cloud messed up

### ISSUE THREAD

**Issue by NilsRublein** [sirselim/lyritical#1]
Hey there, I tried out your code for a project and seems to work properly. It doesn't find all artists and the word clouds are also messed up, thus implying that the number of words that are found, etc, are also wrong. Do you know what could be the cause for this? (I'm new to R, as a side note)

Cheers,
Nils

![capture](https://user-images.githubusercontent.com/30392686/40706427-0cd8828e-63ee-11e8-9330-d22a8ee07523.JPG)

**Comment by sirselim** [comment]
Hi Nils,

First off, thanks for taking this for for a spin! It was something I created for fun a few years ago and never expected it to be used.

I was actually looking at this again the other day as part of another project and I realised that changes to the lyric hosting website have made my code produce some 'funny' results. I have a couple of ideas for fixes and will try to get to this over the weekend. The big Issue is that the host website had changed how it formats its urls.

In terms of the word cloud it looks like a simple text 'cleaning' issue, again probably Induced by the aforementioned changes. That should be an easy fix.

Please keep an eye on the repository for updates, I'd be interested to hear how you get on.

Cheers, 

Miles

**Comment by sirselim** [comment]
I have gone through and overhauled the code. The biggest change is the use of the great [geniusR](https://github.com/JosiahParry/geniusR) package to grab lyric data from genius.com.

There are functions to create wordclouds for a song as well as an album from a given artist. I am working on getting the artist wordcloud function up and running but this will take a little bit of time.

I will update the readme with all information when I get a chance.
